INSERT INTO courses (name, description, teacher_id, department_id, state, created_at, last_update)
VALUES
('Mathematics 101', 'An introduction to mathematical concepts.', 1, 1, 'ACTIVE', NOW(), NOW()),
('Physics 101', 'Fundamentals of physics with laboratory work.', 2, 1, 'ACTIVE', NOW(), NOW()),
('Chemistry 101', 'Basic concepts of chemistry including experiments.', 3, 1, 'ACTIVE', NOW(), NOW()),
('Biology 101', 'Study of living organisms and life processes.', 4, 2, 'ACTIVE', NOW(), NOW()),
('Computer Science 101', 'Introduction to programming and algorithms.', 5, 2, 'ACTIVE', NOW(), NOW()),
('History 101', 'Overview of world history from ancient to modern times.', 6, 3, 'ACTIVE', NOW(), NOW()),
('Literature 101', 'Study of major literary works and authors.', 7, 3, 'ACTIVE', NOW(), NOW()),
('Art History 101', 'Exploration of art movements and their impacts.', 8, 3, 'ACTIVE', NOW(), NOW()),('Economics 101', 'Principles of micro and macroeconomics.', 9, 4, 'ACTIVE', NOW(), NOW()),
('Business Management 101', 'Fundamentals of managing a business.', 10, 4, 'ACTIVE', NOW(), NOW()),
('Psychology 101', 'Introduction to psychology and human behavior.', 11, 4, 'ACTIVE', NOW(), NOW()),
('Sociology 101', 'Understanding societies and social behavior.', 12, 4, 'ACTIVE', NOW(), NOW()),
('Geography 101', 'Study of the Earth and its features.', 13, 5, 'ACTIVE', NOW(), NOW()),
('Statistics 101', 'Introduction to statistical methods and applications.', 14, 5, 'ACTIVE', NOW(), NOW()),
('Philosophy 101', 'Overview of major philosophical concepts and thinkers.', 15, 5, 'ACTIVE', NOW(), NOW()),
('Political Science 101', 'Understanding government systems and political behavior.', 16, 6, 'ACTIVE', NOW(), NOW()),
('Environmental Science 101', 'Study of environmental issues and sustainability.', 17, 6, 'ACTIVE', NOW(), NOW()),
('Music Theory 101', 'Introduction to music theory and composition.', 18, 6, 'ACTIVE', NOW(), NOW()),
('Statistics for Business 101', 'Applying statistics in business contexts.', 19, 7, 'ACTIVE', NOW(), NOW()),
('Ethics 101', 'Exploration of moral philosophy and ethical dilemmas.', 20, 7, 'ACTIVE', NOW(), NOW()),
('Creative Writing 101', 'Developing writing skills and storytelling techniques.', 21, 7, 'ACTIVE', NOW(), NOW()),
('Web Development 101', 'Basics of HTML, CSS, and JavaScript.', 22, 8, 'ACTIVE', NOW(), NOW()),
('Mobile App Development 101', 'Introduction to building mobile applications.', 23, 8, 'ACTIVE', NOW(), NOW()),
('Game Development 101', 'Fundamentals of game design and programming.', 24, 8, 'ACTIVE', NOW(), NOW()),
('Data Science 101', 'Introduction to data analysis and visualization.', 25, 8, 'ACTIVE', NOW(), NOW()),
('Machine Learning 101', 'Basics of machine learning algorithms and techniques.', 26, 9, 'ACTIVE', NOW(), NOW()),
('Artificial Intelligence 101', 'Introduction to AI concepts and applications.', 27, 9, 'ACTIVE', NOW(), NOW()),
('Networking 101', 'Fundamentals of computer networking.', 28, 9, 'ACTIVE', NOW(), NOW()),
('Cybersecurity 101', 'Introduction to cybersecurity principles.', 29, 10, 'ACTIVE', NOW(), NOW()),
('Information Systems 101', 'Overview of information systems and technology.', 30, 10, 'ACTIVE', NOW(), NOW()),
('Digital Marketing 101', 'Basics of marketing in the digital age.', 31, 10, 'ACTIVE', NOW(), NOW()),
('Project Management 101', 'Fundamentals of managing projects effectively.', 32, 11, 'ACTIVE', NOW(), NOW()),
('Operations Management 101', 'Overview of operations in organizations.', 33, 11, 'ACTIVE', NOW(), NOW()),
('Supply Chain Management 101', 'Introduction to supply chain concepts.', 34, 11, 'ACTIVE', NOW(), NOW()),
('Financial Accounting 101', 'Basics of accounting principles and practices.', 35, 12, 'ACTIVE', NOW(), NOW()),
('Managerial Accounting 101', 'Understanding accounting for managerial decisions.', 36, 12, 'ACTIVE', NOW(), NOW()),
('Investment Management 101', 'Overview of investment principles and strategies.', 37, 12, 'ACTIVE', NOW(), NOW()),
('Corporate Finance 101', 'Introduction to financial management in corporations.', 38, 12, 'ACTIVE', NOW(), NOW()),
('Business Ethics 101', 'Exploration of ethics in business practices.', 39, 13, 'ACTIVE', NOW(), NOW()),
('Social Media Management 101', 'Managing social media platforms for businesses.', 40, 13, 'ACTIVE', NOW(), NOW()),
('Content Creation 101', 'Basics of creating content for online platforms.', 41, 13, 'ACTIVE', NOW(), NOW()),
('Graphic Design 101', 'Introduction to graphic design principles and techniques.', 42, 14, 'ACTIVE', NOW(), NOW()),
('Photography 101', 'Basics of photography and image editing.', 43, 14, 'ACTIVE', NOW(), NOW()),
('Video Production 101', 'Fundamentals of video production and editing.', 44, 14, 'ACTIVE', NOW(), NOW()),
('Public Speaking 101', 'Developing effective public speaking skills.', 45, 14, 'ACTIVE', NOW(), NOW()),
('Entrepreneurship 101', 'Overview of starting and managing a business.', 46, 15, 'ACTIVE', NOW(), NOW()),
('E-commerce 101', 'Basics of online business practices and strategies.', 47, 15, 'ACTIVE', NOW(), NOW()),
('Human Resources Management 101', 'Understanding HR principles and practices.', 48, 15, 'ACTIVE', NOW(), NOW()),
('Leadership Skills 101', 'Developing leadership and management skills.', 49, 15, 'ACTIVE', NOW(), NOW()),
('Conflict Resolution 101', 'Strategies for resolving conflicts effectively.', 50, 16, 'ACTIVE', NOW(), NOW()),
('Interpersonal Skills 101', 'Building effective communication and relationships.', 51, 16, 'ACTIVE', NOW(), NOW()),
('Time Management 101', 'Effective strategies for managing time.', 52, 16, 'ACTIVE', NOW(), NOW()),
('Stress Management 101', 'Techniques for managing stress and wellness.', 53, 16, 'ACTIVE', NOW(), NOW()),
('Child Development 101', 'Overview of child development stages.', 54, 17, 'ACTIVE', NOW(), NOW()),
('Special Education 101', 'Understanding special education principles.', 55, 17, 'ACTIVE', NOW(), NOW()),
('Health Education 101', 'Basics of health education and promotion.', 56, 17, 'ACTIVE', NOW(), NOW()),
('Nutrition 101', 'Introduction to nutrition and dietary principles.', 57, 17, 'ACTIVE', NOW(), NOW()),
('Fitness 101', 'Basics of fitness and exercise principles.', 58, 18, 'ACTIVE', NOW(), NOW()),
('Culinary Arts 101', 'Introduction to culinary skills and techniques.', 59, 18, 'ACTIVE', NOW(), NOW()),
('Fashion Design 101', 'Basics of fashion design and marketing.', 60, 18, 'ACTIVE', NOW(), NOW()),
('Interior Design 101', 'Overview of interior design principles.', 61, 19, 'ACTIVE', NOW(), NOW()),
('Architecture 101', 'Introduction to architectural design and theory.', 62, 19, 'ACTIVE', NOW(), NOW()),
('Urban Planning 101', 'Understanding urban planning and development.', 63, 19, 'ACTIVE', NOW(), NOW()),
('Civil Engineering 101', 'Fundamentals of civil engineering principles.', 64, 19, 'ACTIVE', NOW(), NOW()),
('Electrical Engineering 101', 'Introduction to electrical engineering concepts.', 65, 20, 'ACTIVE', NOW(), NOW()),
('Mechanical Engineering 101', 'Overview of mechanical engineering principles.', 66, 20, 'ACTIVE', NOW(), NOW()),
('Chemical Engineering 101', 'Basics of chemical engineering principles.', 67, 20, 'ACTIVE', NOW(), NOW()),
('Aerospace Engineering 101', 'Fundamentals of aerospace engineering concepts.', 68, 20, 'ACTIVE', NOW(), NOW()),
('Environmental Engineering 101', 'Introduction to environmental engineering principles.', 69, 21, 'ACTIVE', NOW(), NOW()),
('Agricultural Engineering 101', 'Overview of agricultural engineering concepts.', 70, 21, 'ACTIVE', NOW(), NOW()),
('Petroleum Engineering 101', 'Basics of petroleum engineering principles.', 71, 21, 'ACTIVE', NOW(), NOW()),
('Software Engineering 101', 'Introduction to software engineering practices.', 72, 22, 'ACTIVE', NOW(), NOW()),
('Database Management 101', 'Understanding database design and management.', 73, 22, 'ACTIVE', NOW(), NOW()),
('Cloud Computing 101', 'Basics of cloud computing and services.', 74, 22, 'ACTIVE', NOW(), NOW()),
('DevOps 101', 'Introduction to DevOps practices and tools.', 75, 22, 'ACTIVE', NOW(), NOW()),
('Information Security 101', 'Fundamentals of information security principles.', 76, 23, 'ACTIVE', NOW(), NOW()),
('Web Security 101', 'Overview of web security practices and tools.', 77, 23, 'ACTIVE', NOW(), NOW()),
('Data Privacy 101', 'Understanding data privacy principles and regulations.', 78, 23, 'ACTIVE', NOW(), NOW()),
('Blockchain 101', 'Introduction to blockchain technology and applications.', 79, 23, 'ACTIVE', NOW(), NOW()),
('Artificial Intelligence Ethics 101', 'Exploring ethical considerations in AI.', 80, 24, 'ACTIVE', NOW(), NOW()),
('Robotics 101', 'Introduction to robotics and automation.', 81, 24, 'ACTIVE', NOW(), NOW()),
('Augmented Reality 101', 'Basics of augmented reality technologies.', 82, 24, 'ACTIVE', NOW(), NOW()),
('Virtual Reality 101', 'Understanding virtual reality and its applications.', 83, 24, 'ACTIVE', NOW(), NOW()),
('Quantum Computing 101', 'Introduction to quantum computing concepts.', 84, 25, 'ACTIVE', NOW(), NOW()),
('Game Theory 101', 'Fundamentals of game theory and decision-making.', 85, 25, 'ACTIVE', NOW(), NOW()),
('Systems Analysis 101', 'Understanding systems analysis and design.', 86, 25, 'ACTIVE', NOW(), NOW()),
('Network Security 101', 'Overview of network security principles.', 87, 25, 'ACTIVE', NOW(), NOW()),
('Ethical Hacking 101', 'Introduction to ethical hacking techniques.', 88, 26, 'ACTIVE', NOW(), NOW()),
('Digital Forensics 101', 'Understanding digital forensics principles and practices.', 89, 26, 'ACTIVE', NOW(), NOW()),
('Cloud Security 101', 'Basics of cloud security practices and tools.', 90, 26, 'ACTIVE', NOW(), NOW()),
('User Experience Design 101', 'Introduction to UX design principles.', 91, 26, 'ACTIVE', NOW(), NOW()),
('Game Design 101', 'Overview of game design concepts and practices.', 92, 27, 'ACTIVE', NOW(), NOW()),
('Animation 101', 'Basics of animation techniques and software.', 93, 27, 'ACTIVE', NOW(), NOW()),
('Film Studies 101', 'Exploration of film theory and history.', 94, 27, 'ACTIVE', NOW(), NOW()),
('Creative Technologies 101', 'Understanding creative technology applications.', 95, 28, 'ACTIVE', NOW(), NOW()),
('Interdisciplinary Studies 101', 'Exploring connections between disciplines.', 96, 28, 'ACTIVE', NOW(), NOW()),
('Global Studies 101', 'Overview of global issues and challenges.', 97, 28, 'ACTIVE', NOW(), NOW()),
('Cultural Studies 101', 'Understanding culture and its influences.', 98, 28, 'ACTIVE', NOW(), NOW()),
('Gender Studies 101', 'Exploring gender issues and perspectives.', 99, 29, 'ACTIVE', NOW(), NOW()),
('Sustainable Development 101', 'Introduction to sustainable development principles.', 100, 29, 'ACTIVE', NOW(), NOW());
