package org.una.programmingIII.UTEMP_Project.models;

public enum UserPermission {

    // TOTAL PERMISSIONS
    ALL_PERMISSIONS,

    MANAGE_USERS,
    MANAGE_UNIVERSITIES,
    MANAGE_FACULTIES,
    MANAGE_DEPARTMENTS,
    MANAGE_COURSES,
    MANAGE_ASSIGNMENTS,
    MANAGE_SUBMISSIONS,
    MANAGE_GRADES,
    MANAGE_PERMISSIONS,

    //  -------------------------
    //  |  COMBINED PERMISSIONS |
    //  -------------------------

    // TEACHER COURSE PERMISSIONS
    GET_ALL_COURSES_OF_TEACHER,
    ADD_COURSE_TO_TEACHER,
    REMOVE_COURSE_TO_TEACHER,

    // STUDENT COURSE PERMISSIONS
    GET_ALL_STUDENT_ENROLLMENTS,
    ADD_COURSE_TO_STUDENT,
    REMOVE_COURSE_TO_STUDENT,

    // UNIVERSITY FACULTY PERMISSIONS
    GET_ALL_UNIVERSITY_FACILITIES,
    ADD_FACULTY_TO_UNIVERSITY,
    REMOVE_FACULTY_TO_UNIVERSITY,

    // FACULTY DEPARTMENT PERMISSIONS
    GET_ALL_FACULTY_DEPARTMENTS,
    ADD_DEPARTMENT_TO_FACULTY,
    REMOVE_DEPARTMENT_TO_FACULTY,

    // DEPARTMENT COURSE PERMISSIONS
    GET_ALL_DEPARTMENT_COURSES,
    ADD_COURSE_TO_DEPARTMENT,
    REMOVE_COURSE_TO_DEPARTMENT,

    // COURSE ASSIGNMENT PERMISSIONS
    GET_ALL_COURSE_ASSIGNMENTS,
    ADD_ASSIGNMENT_TO_COURSE,
    REMOVE_ASSIGNMENT_TO_COURSE,

    // ASSIGNMENT SUBMISSION PERMISSIONS
    GET_ALL_ASSIGNMENT_SUBMISSIONS,
    ADD_SUBMISSION_TO_ASSIGNMENT,
    REMOVE_SUBMISSION_TO_ASSIGNMENT,

    // SUBMISSION GRADE PERMISSIONS
    GET_ALL_SUBMISSION_GRADES,
    ADD_FILE_TO_SUBMISSION,
    ADD_GRADE_TO_SUBMISSION,
    REMOVE_FILE_TO_SUBMISSION,
    REMOVE_GRADE_TO_SUBMISSION,

    // USER NOTIFICATION PERMISSIONS
    GET_NOTIS_OF_USER,
    ADD_NOTI_TO_USER,
    REMOVE_NOTI_TO_USER,
    MARK_NOTI_AS_READ,
    SEND_NOTI_TO_USER,

    //  -----------------------
    //  |  UNIQUE PERMISSIONS |
    //  -----------------------

    // USER PERMISSIONS
    GET_ALL_USERS,
    GET_USER_BY_ID,
    GET_STUDENT_BY_IDENTIFICATION_NUMBER,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,

    // UNIVERSITY PERMISSIONS
    GET_ALL_UNIVERSITIES,
    GET_UNIVERSITY_BY_ID,
    CREATE_UNIVERSITY,
    UPDATE_UNIVERSITY,
    DELETE_UNIVERSITY,

    // FACULTY PERMISSIONS
    GET_ALL_FACULTIES,
    GET_FACULTY_BY_ID,
    CREATE_FACULTY,
    UPDATE_FACULTY,
    DELETE_FACULTY,

    // DEPARTMENT PERMISSIONS
    GET_ALL_DEPARTMENTS,
    GET_DEPARTMENT_BY_ID,
    CREATE_DEPARTMENT,
    UPDATE_DEPARTMENT,
    DELETE_DEPARTMENT,

    // COURSE PERMISSIONS
    GET_ALL_COURSES,
    GET_COURSE_BY_ID,
    CREATE_COURSE,
    UPDATE_COURSE,
    DELETE_COURSE,

    // ASSIGNMENT PERMISSIONS
    GET_ALL_ASSIGNMENTS,
    GET_ASSIGNMENT_BY_ID,
    CREATE_ASSIGNMENT,
    UPDATE_ASSIGNMENT,
    DELETE_ASSIGNMENT,

    // SUBMISSION PERMISSIONS
    GET_ALL_SUBMISSIONS,
    GET_SUBMISSION_BY_ID,
    CREATE_SUBMISSION,
    UPDATE_SUBMISSION,
    DELETE_SUBMISSION,

    // GRADE PERMISSIONS
    GET_ALL_GRADES,
    GET_GRADE_BY_ID,
    CREATE_GRADE,
    UPDATE_GRADE,
    DELETE_GRADE,

    // ENROLLMENT PERMISSIONS
    GET_ALL_ENROLLMENTS,
    GET_ALL_ENROLLMENTS_TO_COURSE,
    GET_ALL_ENROLLMENTS_TO_STUDENT,
    GET_ENROLLMENT_BY_ID,
    CREATE_ENROLLMENT,
    UPDATE_ENROLLMENT,
    DELETE_ENROLLMENT,

    // FILE PERMISSIONS
    GET_FILE_BY_ID,
    UPLOAD_FILE,
    DOWNLOAD_FILE,
    UPDATE_FILE,
    DELETE_FILE,

    // NOTIFICATION PERMISSIONS
    GET_ALL_NOTIS,
    GET_NOTI_BY_ID,
    CREATE_NOTI,
    UPDATE_NOTI,
    DELETE_NOTI,
}
